name: Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/$GCP_PROJECT_ID/cloud-backend ./backend
        echo "$GCP_SA_KEY" | base64 -d > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud auth configure-docker
        docker push gcr.io/$GCP_PROJECT_ID/cloud-backend

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials gke-cluster --region=$GCP_REGION
        kubectl apply -f k8s/deployment.yaml
